<?php

/**
 * @file
 * A module that glues together various SEO modules in a unified interface.
 */

/**
 * Implements hook_form_alter().
 */
function seo_ui_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Create a vertical tab for node edit forms
  if (preg_match('#node_(.*?)_form#e', $form_id, $match)) {
    // Establish the SEO vertical tab
    $form['seo_vtab'] = array(
      '#type' => 'details',
      '#title' => t('Search engine optimization (SEOPathauto      '#group' => 'advanced',
      '#attributes' => array(
        'class' => array(
          'seo-settings'
        )
      ),
      '#weight' => 50,
    );
  }
  // Alter node or taxonomy term forms
  if (preg_match('#node_(.*?)_form#e', $form_id, $match) || preg_match('#taxonomy_term_(.*?)_form#e', $form_id, $match)) {
    // Path
    _seo_ui_alter_path($form, $form_state, $form_id);
  }
}


/**
 * Path and Pathauto node alters.
 */
function _seo_ui_alter_path(&$form, $form_state, $form_id) {
  if (\Drupal::moduleHandler()->moduleExists('path')) {
    // Add the new tab to the vertical SEO tab if it exists.
    if (isset($form['seo_vtab'])) {$form['path']['#type'] = 'details';
      $form['path']['#title'] = 'URL Settings';
      $form['path']['#weight'] = 0;
      $form['path']['#open'] = TRUE;
      if (isset($form['path']['widget']['0']['alias'])) {
        $form['path']['widget']['0']['alias']['#weight'] = 2;
        $form['path']['widget']['0']['alias']['#description'] = t('Specify an alternative URL by which this content can be accessed. <b>Use a relative path and remove the trailing slash</b>');
      }
      // ungroup the path item
      unset($form['path']['#group']);
      // Move the form and unset the original
      $form['seo_vtab']['path'] = $form['path'];
      unset($form['path']);
      unset($form['path_settings']);
    }
  }
}
